### ISSUE TITLE
Allow searching Data Request transactions by their bytecode's SHA-256 hash

### ISSUE THREAD

**Issue by guidiaz** [drcpu-github/witnet-explorer-frontend#1]
This way, the user would get a list of all Data Request transactions that contained the corresponding bytecode.

One possible benefit of this issue is that it would enable anyone knowning the bytecode of a price feed to trace all the transactions that solved that particular price feed, and therefore the historical values of that price feed, as well any eventual faulty results in time. 

For instance, using the [`Price-BTC/USD-6`](https://github.com/witnet/witnet-price-feed-examples/blob/master/requests/BtcUsdPrice.js) as a reference:
- Data request bytecode: `0adb0312560801123a68747470733a2f2f6170692e62696e616e63652e636f6d2f6170692f76332f7469636b65722f70726963653f73796d626f6c3d425443555344541a168418778218646570726963658218571a000f4240185b124d0801122c68747470733a2f2f6170692e62697466696e65782e636f6d2f76312f7075627469636b65722f6274637573641a1b8418778218646a6c6173745f70726963658218571a000f4240185b12630801123268747470733a2f2f6170692e6b72616b656e2e636f6d2f302f7075626c69632f5469636b65723f706169723d4254435553441a2b87187782186666726573756c7482186668585842545a55534482186161618216008218571a000f4240185b12480801122d68747470733a2f2f7777772e6269747374616d702e6e65742f6170692f76322f7469636b65722f6274637573641a15841877821864646c6173748218571a000f4240185b12650801124068747470733a2f2f6170692e626974747265782e636f6d2f6170692f76312e312f7075626c69632f6765747469636b65723f6d61726b65743d5553442d4254431a1f85187782186666726573756c74821864644c6173748218571a000f4240185b1a0d0a0908051205fa402000001003220d0a0908051205fa40200000100310c0843d180a20c0843d28463080e497d012`
- SHA-256 hash: **`53be15928e684d456f8b7973a684834385a14d539c92b5e468029e68c54ab32a`**

**Comment by drcpu-github** [comment]
I like this. @parodyBit suggested a similar feature a while ago where you could search for API endpoints used in data requests, but that is rather difficult to implement. This is significantly easier while achieving a very similar end result. I'll have to think about the best design to implement this functionality, but consider it placed on my to do list.

**Comment by drcpu-github** [comment]
As per commit 679436d98c4c6a273fc46aad6fb433142bf3d163 and follow ups, this is now implemented.
