### ISSUE TITLE
Show headers on HTTP/GET retrievals (where used)

### ISSUE THREAD

**Issue by guidiaz** [drcpu-github/witnet-explorer-frontend#18]
Example:
- https://witnet.network/search/4594d8d8c945d0f05997fadafe68bbda562b9ad2aa3790a442c7d0ca0ba1afe4
- Missing header: `If-None-Match: "QmRrhtSv8RqSueNYq6cnMfnVJu1RAyjw53suDfuYiqPnEr"`

**Comment by drcpu-github** [comment]
Implemented in https://github.com/drcpu-github/witnet-explorer-frontend/commit/dc69803eef6b0a7a3d5cb9aaab064894afb712a9
