### ISSUE TITLE
Select proper proper View Tab when some search matches a single DR

### ISSUE THREAD

**Issue by guidiaz** [drcpu-github/witnet-explorer-frontend#26]
For instance, if the matched hash identifies a Tally transaction, show the "Tally" tab instead of the "Data request" one:
- https://witnet.network/search/19114e1588ff8f8f5ff75b675951c76040598178a8cb76d3c146904988778f05

Idem if matched hash identifies either a Commit or a Reveal transaction.

**Comment by drcpu-github** [comment]
Already implemented in the 1.5 release.
