### ISSUE TITLE
Shown block timestamps gaps 45 seconds later in time

### ISSUE THREAD

**Issue by guidiaz** [drcpu-github/witnet-explorer-frontend#4]
Block timestamps seem not being reported correctly, stating 45 seconds more than the actual unix timestamp of the corresponding epoch.

For instance, see this DR inserted within a block on epoch 1004820: https://witnet.network/search/4fa3df8f187a0a4b13c6621285778531045ce9ddd209b71ba5098b96f55ccb7c. For what we know, epoch 1004820 corresponds to a timestamp value of `1647882900`, or  "Mon Mar 21 2022 17:15:00 GMT+0000". However, Witnet Explorer shows "17:15:45 21/03/2022 (epoch: 1004820)" as timestamp.

**Comment by drcpu-github** [comment]
This was resolved, the Witnet explorer shows the timestamp at block consolidation time rather than the epoch start time.
